#
# start the ethereum network
#

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files: 
    - global-vars.yml
  tasks:
    - name: start aws-chain instances
      local_action:
        module: ec2
        state: running
        region: "{{ aws_parameters.region }}"
        instance_ids: "{{ hostvars[item]['ec2_id'] }}"
        wait: true
      with_items: 
        - "{{ groups['tag_aws_chain_node_true'] | default([]) }}"

    - name: refresh EC2 cache
      command: ./ec2.py --refresh-cache

    - name: refresh in-memory EC2 cache
      meta: refresh_inventory


- name: gather facts on mining nodes
  hosts: tag_aws_chain_mining_node_true
  gather_facts: true

- name: install static list of peer nodes on gateway node
  hosts: tag_aws_chain_gateway_node_true
  gather_facts: true
  vars_files: 
    - global-vars.yml
  tasks:
    - name: create static list of peer nodes 
      template:
        src: roles/gateway/templates/static-nodes.json.j2
        dest: "{{ geth.data_dir }}/static-nodes.json"

- name: start geth service on gateway and mining nodes
  hosts: tag_aws_chain_node_true
  vars_files: 
    - global-vars.yml
  tasks:
    - name: start geth service
      become: true
      systemd:
        state: started
        name: geth
