#
#  tasks for mining nodes
# 

- name: set hostname 
  # TODO: should also add an entry in /etc/hosts, otherwise sudo reports that it can't
  # resolve the host name
  hostname: name="aws-chain-mining-node-{{ groups.tag_aws_chain_mining_node_true.index(inventory_hostname) }}"
  become: true

- name: create a miner account
  vars:
    password_file: /home/ubuntu/miner-password
  # 'miner' is the password for the created mining account. Shouldn't be included
  # in the playbook for a *real* ethereum chain, obviously.
  shell: | 
    echo miner > {{ password_file }} 
    geth --datadir {{ geth.data_dir }}  --password {{ password_file }} account new
    rm {{ password_file }} 
 
- name: extract miner account 
  shell: |
    geth --datadir {{ geth.data_dir }} account list \
    | grep "Account #0" \
    | sed -n 's/.*--\([0-9a-f]\+\)$/\1/p'
  register: extract_miner_account_result

- name: install the geth wrapper for mining
  vars:
    geth_etherbase: "{{ extract_miner_account_result.stdout }}"
  template: 
    src: geth.sh.j2
    dest: /home/ubuntu/geth.sh
    mode: "u=rwx,g=r,o=r"

