
#
# common tasks on ethereum nodes
#

- name: add ethereum apt repository
  become: true
  apt_repository: repo="ppa:ethereum/ethereum" state=present

- name: install ethereum apt package 
  become: true
  apt:
    name: ethereum
    update_cache: yes

- name: copy genesis JSON
  copy: src=genesis.json dest=/home/ubuntu/genesis.json

- name: create geth data directory
  file: path="{{ geth_data_dir }}" state=directory

- name: init chain
  shell: geth --datadir {{ geth_data_dir }} init genesis.json


- name: ensure custom facts directory exists
  become: true
  file: >
    path=/etc/ansible/facts.d
    recurse=yes
    state=directory

- name: install custom facts module for enode ID
  become: true
  template: >
    src=enode_id.fact.j2
    dest=/etc/ansible/facts.d/enode_id.fact
    mode=0755

- name: reload ansible local
  setup: filter=ansible_local







